apiVersion: v1
kind: PersistentVolume
metadata:
  name: tz-local-pv
spec:
  capacity:
    storage: 10Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /vagrant/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: ["k8s-master", "node-1"]

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tz-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Mi

